#!/bin/sh
mount -t sysfs sysfs /sys
mount -t proc proc /proc
mount -t tmpfs none /tmp -o mode=1777
mount -t devtmpfs udev /dev
mount -t devpts none /dev/pts
sysctl -w kernel.printk="2 4 1 7"
clear
echo -e "Welcome to \\e[34mWave \\e[32mLinux \\e[31mLive\\e[0m (/init)"
/bin/sh
poweroff -f
